services:
  - type: web
    name: stockbase
    runtime: java
    rootDir: backend
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/stockbase-api-1.0.0.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
